In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report
import seaborn as sns

In [2]:
data=pd.read_csv('test.csv')

In [3]:
data

,label,X_min,X_max,X_range,X_mean,X_rms,X_std,Y_min,Y_max,Y_range,...,Z_jerk_mean,Z_jerk_rms,Z_jerk_std,total_jerk_min,total_jerk_max,total_jerk_range,total_jerk_mean,total_jerk_rms,total_jerk_std,timestamp_range
0,6,-0.59,0.58,1.18,-0.12,0.17,0.12,-0.58,0.3,0.88,...,-0.08,8.25,8.25,0.33,105.18,104.84,11.57,23.14,20.04,0.22
1,6,-0.59,0.52,1.11,-0.12,0.17,0.12,-0.58,0.3,0.88,...,-0.01,8.29,8.29,0.33,105.18,104.84,11.80,23.38,20.19,0.22
2,3,-0.59,0.57,1.16,-0.09,0.15,0.12,-0.58,0.3,0.88,...,0.18,6.86,6.86,0.28,105.18,104.89,11.18,20.97,17.74,0.22
3,3,-0.59,0.57,1.16,-0.09,0.15,0.12,-0.58,0.3,0.88,...,0.12,6.79,6.79,0.28,105.18,104.89,11.01,20.80,17.65,0.22
4,3,-0.59,0.52,1.11,-0.09,0.15,0.12,-0.58,0.3,0.88,...,-0.02,6.46,6.46,0.28,105.18,104.89,10.59,19.75,16.68,0.22
5,3,-0.59,0.55,1.14,-0.09,0.15,0.12,-0.58,0.3,0.88,...,0.11,6.11,6.11,0.28,105.18,104.89,10.35,19.40,16.40,0.22
6,3,-0.59,0.58,1.18,-0.09,0.15,0.12,-0.58,0.3,0.88,...,0.22,5.88,5.88,0.28,105.18,104.89,9.93,18.25,15.32,0.22

In [4]:
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay

In [5]:
x=data.drop(['label'], axis=1)
y=data['label']

In [6]:
scale=StandardScaler()
x=scale.fit_transform(x)

In [7]:
import tensorflow as tf

2024-07-08 04:03:09.364226: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-08 04:03:09.365575: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-08 04:03:09.387578: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-08 04:03:09.387600: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-08 04:03:09.387615: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-08 04:03:09.391791: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-08 04:03:09.392330: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-08 04:03:09.915040: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [8]:
# Load the TensorFlow Lite model
interpreter = tf.lite.Interpreter(model_path='model_quantized.tflite')
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

In [9]:
predicted_labels = []

In [10]:
x_test_float32 = x.astype(np.float32)

In [26]:
def classify_input(input_data):
    # Ensure the input data is in the correct shape and type
    input_data = np.array(input_data, dtype=np.float32).reshape(input_details[0]['shape'])

    # Set the tensor to the input data
    interpreter.set_tensor(input_details[0]['index'], input_data)

    # Run the inference
    interpreter.invoke()

    # Get the output tensor
    output_data = interpreter.get_tensor(output_details[0]['index'])

    # Assume the output_data is of shape (1, num_classes)
    predictions = np.squeeze(output_data)

    # Get the maximum probability and its corresponding class index
    max_prob = np.max(predictions)
    class_idx = np.argmax(predictions)

#     # Check if the max probability is greater than 0.70
#     if max_prob > 0.9999:
#         return class_idx  # Return the class index (0 to 7 for 8 classes)
#     else:
#         return 8  # Return 9th class (index 8)
    
    return max_prob

In [27]:
classification_results = [classify_input(row) for row in x_test_float32]

In [28]:
classification_results

[0.9999995, 0.9999634, 0.99995303, 0.9999585, 0.9029877, 0.9999999, 0.47330895]