In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('combined_features_data.csv')

In [3]:
data['label']=data['label'].astype('int')

In [4]:
data.reset_index(inplace=True)
data.drop(['index'], axis=1, inplace=True)

In [5]:
data

,label,X_min,X_max,X_range,X_mean,X_rms,X_std,Y_min,Y_max,Y_range,...,Z_jerk_mean,Z_jerk_rms,Z_jerk_std,total_jerk_min,total_jerk_max,total_jerk_range,total_jerk_mean,total_jerk_rms,total_jerk_std,timestamp_range
0,3,-1.004375,0.138634,1.143009,-0.271257,0.367041,0.248950,-1.232137,0.086563,1.318700,...,-0.139728,13.207294,13.296703,-34.995523,27.094139,62.089663,-1.106926,13.783655,13.832920,0.803
1,3,-0.990767,0.127101,1.117868,-0.423896,0.505179,0.276519,-1.185982,0.093986,1.279967,...,0.137329,16.917456,17.022300,-45.337704,47.307691,92.645395,-0.212084,16.781165,16.884373,0.880
2,3,-0.720209,0.214299,0.934508,-0.271104,0.341752,0.209499,-1.566424,0.114125,1.680549,...,0.893990,16.324505,16.411271,-30.954806,37.832124,68.786930,1.058925,13.647771,13.699507,0.803
3,3,-0.496083,0.153754,0.649837,-0.224294,0.278918,0.167294,-0.711852,0.049919,0.761771,...,0.355520,5.332928,5.369220,-15.037770,11.633259,26.671029,-0.374330,6.356843,6.403241,0.605
4,3,-0.861475,0.202574,1.064049,-0.318783,0.396607,0.237407,-0.897966,0.092182,0.990147,...,-0.623661,10.635301,10.682335,-38.667600,37.477062,76.144662,0.080205,11.699858,11.771581,0.891
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3730,5,-0.834887,1.088238,1.923125,-0.198314,0.477376,0.437464,-1.312318,0.126992,1.439310,...,0.153924,14.603337,14.711096,-23.881253,20.799001,44.680255,-0.099162,8.639718,8.703382,0.737
3731,5,-1.592273,0.800989,2.393262,-0.223964,0.589055,0.549660,-1.284093,0.101797,1.385890,...,-0.226635,10.115621,10.202977,-27.472703,21.099744,48.572448,0.986131,11.553537,11.613701,0.616
3732,5,-1.145478,0.834240,1.979718,-0.288274,0.501753,0.413404,-1.466980,0.148195,1.615175,...,1.205375,22.000511,22.113431,-43.758976,54.160332,97.919308,0.538583,16.613627,16.715227,0.825
3733,5,-0.828272,0.844807,1.673079,-0.121973,0.453033,0.439700,-1.333032,0.172730,1.505761,...,0.763718,15.787246,15.891478,-17.396541,26.624261,44.020802,0.045035,8.635763,8.702850,0.704
3734,5,-1.113732,0.943032,2.056763,-0.108171,0.509870,0.502692,-1.917839,0.248420,2.166259,...,-2.647551,29.843125,29.989685,-62.317138,37.209362,99.526500,-0.923052,21.212058,21.380342,0.616

In [6]:
data = data[~data['label'].isin([1, 3, 5])]

In [7]:
label_mapping = {2: 1, 4: 2, 6: 3, 7: 4}

In [8]:
data['label'] = data['label'].replace(label_mapping)

/tmp/ipykernel_10529/3664380128.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['label'] = data['label'].replace(label_mapping)

In [9]:
data['label'].value_counts()

2    591
3    573
1    501
4    452
0    436
Name: label, dtype: int64

In [10]:
data.to_csv('/home/ettexham/Desktop/Thesis/Accelerometer Data/DataSet/Clockwise_Notebooks/ML_Data_CW.csv', index=False)